# Generated by Django 4.2.30 on 2026-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['invitee', 'status'], name='invites_inv_invitee_ede105_idx'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['invitee', 'kind', 'status'], name='invites_inv_invitee_c48455_idx'),
        ),
    ]
