# Generated by Django 6.0.4 on 2026-04-20 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('date', models.DateTimeField(verbose_name='data')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='groups.group')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='artista')),
                ('key', models.CharField(blank=True, choices=[('C', 'Dó Maior'), ('Cm', 'Dó Menor'), ('C#', 'Dó# Maior'), ('C#m', 'Dó# Menor'), ('Db', 'Réb Maior'), ('D', 'Ré Maior'), ('Dm', 'Ré Menor'), ('D#m', 'Ré# Menor'), ('Eb', 'Mib Maior'), ('E', 'Mi Maior'), ('Em', 'Mi Menor'), ('F', 'Fá Maior'), ('Fm', 'Fá Menor'), ('F#', 'Fá# Maior'), ('F#m', 'Fá# Menor'), ('G', 'Sol Maior'), ('Gm', 'Sol Menor'), ('G#m', 'Sol# Menor'), ('Ab', 'Láb Maior'), ('A', 'Lá Maior'), ('Am', 'Lá Menor'), ('A#m', 'Lá# Menor'), ('Bb', 'Sib Maior'), ('B', 'Si Maior'), ('Bm', 'Si Menor')], max_length=5, verbose_name='tonalidade')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('link', models.URLField(blank=True, verbose_name='link')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='groups.group')),
            ],
            options={
                'verbose_name': 'música',
                'verbose_name_plural': 'músicas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('declined', 'Recusado')], default='pending', max_length=20)),
                ('role_in_event', models.CharField(blank=True, max_length=50, verbose_name='papel no evento')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to='events.event')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='groups.membership')),
            ],
            options={
                'verbose_name': 'membro do evento',
                'verbose_name_plural': 'membros do evento',
                'unique_together': {('event', 'membership')},
            },
        ),
        migrations.CreateModel(
            name='EventSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_songs', to='events.event')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_songs', to='events.song')),
            ],
            options={
                'verbose_name': 'música do evento',
                'verbose_name_plural': 'músicas do evento',
                'ordering': ['order'],
                'unique_together': {('event', 'song')},
            },
        ),
    ]
