# Generated by Django 4.2.30 on 2026-04-20 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_profile_and_instruments'),
        ('events', '0005_eventmember_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.URLField(blank=True, help_text='URL opcional (streaming, vídeo, partitura, etc.).', verbose_name='link de referência'),
        ),
        migrations.CreateModel(
            name='SongSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='artista')),
                ('key', models.CharField(blank=True, choices=[('C', 'Dó Maior'), ('Cm', 'Dó Menor'), ('C#', 'Dó# Maior'), ('C#m', 'Dó# Menor'), ('Db', 'Réb Maior'), ('D', 'Ré Maior'), ('Dm', 'Ré Menor'), ('D#m', 'Ré# Menor'), ('Eb', 'Mib Maior'), ('E', 'Mi Maior'), ('Em', 'Mi Menor'), ('F', 'Fá Maior'), ('Fm', 'Fá Menor'), ('F#', 'Fá# Maior'), ('F#m', 'Fá# Menor'), ('G', 'Sol Maior'), ('Gm', 'Sol Menor'), ('G#m', 'Sol# Menor'), ('Ab', 'Láb Maior'), ('A', 'Lá Maior'), ('Am', 'Lá Menor'), ('A#m', 'Lá# Menor'), ('Bb', 'Sib Maior'), ('B', 'Si Maior'), ('Bm', 'Si Menor')], max_length=5, verbose_name='tonalidade')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('link', models.URLField(blank=True, help_text='URL opcional (streaming, vídeo, partitura, etc.).', verbose_name='link de referência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Recusada')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_suggestion', to='events.song', verbose_name='música criada')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_suggestions', to='groups.group')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_suggestions_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='sugerido por')),
            ],
            options={
                'verbose_name': 'sugestão de música',
                'verbose_name_plural': 'sugestões de música',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'group'], name='events_song_status_e52aaf_idx')],
            },
        ),
    ]
