# Generated by Django 4.2.30 on 2026-04-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='sobre mim'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instruments',
            field=models.JSONField(blank=True, default=list, verbose_name='instrumentos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='foto'),
        ),
    ]
