# Generated by Django 4.2.30 on 2026-04-20 19:22

from django.db import migrations


def merge_membership_instrument_into_user(apps, schema_editor):
    Membership = apps.get_model('groups', 'Membership')
    CustomUser = apps.get_model('accounts', 'CustomUser')
    for membership in Membership.objects.all().select_related('user'):
        slug = getattr(membership, 'instrument', '') or ''
        if not slug.strip():
            continue
        user = membership.user
        current = list(user.instruments or [])
        if slug not in current:
            current.append(slug)
            user.instruments = current
            user.save(update_fields=['instruments'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_and_instruments'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(merge_membership_instrument_into_user, noop_reverse),
        migrations.RemoveField(
            model_name='membership',
            name='instrument',
        ),
    ]
