# Generated by Django 4.2.30 on 2026-04-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_add_is_active_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_avatars/', verbose_name='avatar'),
        ),
    ]
